### ISSUE TITLE
create_report() broken in devel

### ISSUE THREAD

**Issue by PeteHaitch** [LuyiTian/scPipe#100]
I don't know how/when this broke because I could've sworn I ran this only a few weeks ago using the devel versions of **scPipe** and **scater**... 
But `create_report()` isn't working for me now using **scPipe** b1862a2c1c19bf186a649af0d08f3157251aaee5 and **scater** v1.9.20

I think one of the reasons is because
https://github.com/LuyiTian/scPipe/blob/master/inst/extdata/report_template.Rmd includes lines like

```R
plotPCA(sce_qc, exprs_values="cpm", colour_by="total_features")
```

At some point, **scater** changed(?) and this needs to be:

```R
plotPCA(sce_qc, run_args = list(exprs_values="cpm"), colour_by="total_features")
```
There are similar issues with the calls to `plotTSNE()` (which also needs to use `run_args = list(...)`) and `trendVar()` (which needs to use `loess.args = list()`).

There may be other compatibility issues that I haven't detected in my quick scan. As far as I can tell there aren't any unit tests or examples that check that `create_report()` is working as intended, which makes it a little hard (for me at least) to debug the issue and be confident I've fixed it.

**Comment by LuyiTian** [comment]
Yes, the report have broken several times due to the parameter changes. They have changed the argument a while ago and removed backward compatibility in recent version. It is a bit annoying that Scater and Scran changing their parameters frequently, and sometimes without any notice and you won't aware until you get an error.

I will check the Rmd code for the report and fix the bugs.

**Comment by LuyiTian** [comment]
fixed https://github.com/LuyiTian/scPipe/commit/8b4c9a30536d025c870afe89eb52afd3dbabe3c2
