### ISSUE TITLE
number of cells and genes

### ISSUE THREAD

**Issue by shokohirosue** [LuyiTian/scPipe#112]
Hi,

I have been processing publicly available 10X single cell RNA seq experiment fastq files using scpipe, then passing it into scran.

Somehow I get only 20000 cells from one sample - is there a reason for this?
Also, the number of genes (number of rows) I get varies.
Why could this be?

Thank you for your help.

Best regards,
Shoko

**Comment by Shians** [comment]
Depending on how you're running the pipeline, but the default option in `sc_detect_bc()` is to only retain the top 10000 most abundant cells. So I assume either you've changed it to 20000 or we've made a mistake in our code somewhere. Try increasing that number, in addition you may need to increase `max_reads` too because we detect barcodes by sampling from the first N reads (default 1,000,000).

This caught my eye just before falling asleep, so don't expect another reply for at least 7 hours. :)

**Comment by shokohirosue** [comment]
Thank you very much!
Sorry, I think I wrote the code sometime ago and forgot what I did.
With number_of_cells 20000, what max_reads would be sensible? I tried 5e+08 - is there any harm by running more?

Also, do you have any idea why the number of genes (rows) are different when I create sce object?

Thank you so much for your help.

**Comment by LuyiTian** [comment]
It depends on the expected number of cells in the data. Most of the 10X datasets won't have 20000 cells. the number is usually 1000~5000. What is the number of cells after you perform QC? 

The number of genes should be the same. but if you performed QC and removed some cells, some genes might have zero counts across all cell and hence removed by scran.

**Comment by shokohirosue** [comment]
Thank you very much for your reply.
Based on their analysis, there should be 8000 cells per sample.

I did not perform any QC so far - as soon as I ran `create_sce_by_dir` the output has different number of genes for each sample in random order for some reason. I looked at gene_count.csv and it already has different number of rows for different samples.

Would you be able to suggest how to troubleshoot this?

Thank you so much.

**Comment by LuyiTian** [comment]
the gene_count.csv only keeps genes with at least one positive count in any cells. so for two different samples, the genes and the order will be different. usually, you need to perform gene filtering in QC, for some clustering and trajectory methods, they perform better with highly variable genes instead of all genes.

you can refer to this paper for QC: https://f1000research.com/articles/5-2122/v1.

**Comment by shokohirosue** [comment]
Thank you for your reply and the QC link.

I would like to combine the samples as those samples are biological replicates.
However, `cbind` does not work on sce object as it requires the rownames to be identical.

So my questions are - 
1) You told me that the number of genes should be the same -  does this mean `create_sce_by_dir` should correct the order and missing genes in gene_count.csv? When I ran the function, the rows of sce object was the same as the rows in gene_count.csv.

2) I would like to reorder the gene names, and add zeros to all the columns of the genes that are not expressed in the sample. Can I just edit gene_count.csv, or is there any other output files in the directory I should edit?

Thank you so much for your help.

**Comment by LuyiTian** [comment]
`create_sce_by_dir` does not change anything. It just read what it is in the gene_count.csv and stores it in an SCE object. You have to write your own R code to deal with it(examples: https://stackoverflow.com/questions/5738773/r-how-to-merge-two-matrix-according-to-their-column-and-row-names).

**Comment by shokohirosue** [comment]
Thank you very much for clarifying this.

Regarding to the argument passed into `sc_detect_bc`, how can I find the optimal `max_reads` from expected number of cells? (What are the underlying assumptions?)
Is there any harm by sampling more than necessary?

Thank you!

**Comment by LuyiTian** [comment]
it just read the cell barcode and count, then detect the enriched cell barcode. To speed things up it will read the first `max_reads` number of reads.
the default parameter should work in most cases. If you have large number of cell like >7000, then you can set a larger `max_reads`.

**Comment by shokohirosue** [comment]
Thank you so much!
