### ISSUE TITLE
Assigning to QC_metrics overrides colData

### ISSUE THREAD

**Issue by Shians** [LuyiTian/scPipe#34]
Example code:

    library(scPipe)
    
    data("sc_sample_data")
    data("sc_sample_qc")
    sce = SingleCellExperiment(assays = list(counts = as.matrix(sc_sample_data)))
    
    colData(sce) = DataFrame(
        Index = 1:ncol(sce),
        Name = paste("Sample", 1:ncol(sce))
    )
    colData(sce) # assigned colData
    
    QC_metrics(sce) = sc_sample_qc
    colData(sce) # overwritten colData

This seems like undesirable behaviour. It makes it dangerous to run scPipe after other packages using SingleCellExperiment.

**Comment by LuyiTian** [comment]
has been solved by your recent commit

**Comment by LuyiTian** [comment]
@Shians there is an error in unittest http://bioconductor.org/checkResults/release/bioc-LATEST/scPipe/malbec1-checksrc.html. I have fixed this and I think it is caused by you modifying the warning/erorr message and the modified message does not match the proposed on in unittest. So next time when you change the text it will be good to also change the unittest.
