### ISSUE TITLE
Support for Sample Demultiplexing

### ISSUE THREAD

**Issue by DarioS** [LuyiTian/scPipe#97]
If multiple samples have been run in a single sequencing assay, it seems like another software is required for preprocessing (e.g. [`mkfastq`](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/mkfastq)). Can such a task be done with scPipe?

**Comment by LuyiTian** [comment]
It is doable, you can paste the sample index sequence before the index read so the structure becomes <sample_index><10xcell_barcode><UMI> and then specify <sample_index><10xcell_barcode> as the new cell barcode, be careful of the length parameter.

However, I still recommend using mkfastq because it is easier to handle, for the 10X you need to run mkfastq to get the fastq file anyway.

**Comment by DarioS** [comment]
Thanks for the advice. I will use mkfastq.
